import type { IntegrationId, PageId } from "./types";

export interface LocalizedText { zh: string; en: string }
export interface SetupField {
  id: string;
  label: LocalizedText;
  placeholder: string;
  type?: "text" | "password" | "number" | "textarea" | "select";
  options?: Array<{ value: string; label: LocalizedText }>;
  hint: LocalizedText;
  required?: boolean;
}
export interface IntegrationDefinition {
  id: IntegrationId;
  name: LocalizedText;
  icon: string;
  page?: PageId;
  summary: LocalizedText;
  outcome: LocalizedText;
  steps: LocalizedText[];
  fields: SetupField[];
}

const text = (zh: string, en: string): LocalizedText => ({ zh, en });
const singBoxFields: SetupField[] = [
  { id: "endpoint", label: text("sing-box API 地址", "sing-box API endpoint"), placeholder: "http://127.0.0.1:19091", hint: text("只接受 localhost 或回环 IP；Secret 仅从服务器受限配置读取。", "Only localhost or loopback IPs are accepted. The secret is read only from protected server configuration."), required: true },
  { id: "inboundTags", label: text("入站标签", "Inbound tags"), placeholder: "vless-in, vless-reality", hint: text("填写 sing-box 配置中的真实 inbound tag，用逗号分隔；连接只按这些显式标签归类。", "Enter real sing-box inbound tags separated by commas. Connections are classified only by these explicit tags."), required: true },
];
const protocolDefinition = (id: "socks5" | "shadowsocks" | "vmess" | "trojan" | "tuic", name: string, icon: string, summaryZh: string, summaryEn: string): IntegrationDefinition => ({
  id, name: text(name, name), icon, page: "services", summary: text(summaryZh, summaryEn),
  outcome: text(`只有 inbound tag 匹配的真实连接会显示为 ${name}。`, `Only real connections matching configured inbound tags appear as ${name}.`),
  steps: [text(`确认 ${name} 入站已在当前 sing-box 实例启用`, `Confirm the ${name} inbound is enabled in this sing-box instance`), text("填写回环 Clash API", "Enter the loopback Clash API"), text("填写真实 inbound tag", "Enter real inbound tags")],
  fields: singBoxFields,
});

export const integrationDefinitions: IntegrationDefinition[] = [
  { id: "system", name: text("系统指标", "System metrics"), icon: "memory", page: "overview", summary: text("读取主机资源、运行时间与网卡累计计数器。", "Read host resources, uptime, and cumulative interface counters."), outcome: text("总览显示真实主机快照和节点名称。", "The overview shows a live host snapshot and node name."), steps: [text("确认后端仅监听回环地址", "Keep the backend bound to loopback"), text("设置节点显示名称", "Set the node display name"), text("验证 /proc 与文件系统可读", "Verify /proc and filesystem access")], fields: [{ id: "nodeName", label: text("节点显示名称", "Node display name"), placeholder: "Tokyo edge", hint: text("作为总览主标题显示，最长 80 字。", "Shown as the overview title, up to 80 characters."), required: true }] },
 { id: "traffic", name: text("流量采集", "Traffic collection"), icon: "monitoring", page: "traffic", summary: text("每分钟持久化网卡增量，跨重启和计数器归零继续累计。", "Persist interface deltas every minute across restarts and counter resets."), outcome: text("总览显示统一流量额度、当前用量和计费周期。", "The overview shows the shared quota, current usage, and billing cycle."), steps: [text("确认主网卡", "Confirm the primary interface"), text("设置运营商额度与计费周期", "Set the provider quota and billing cycle"), text("如月中接入，填写当前周期已用基线", "If joining mid-cycle, enter the current-cycle baseline")], fields: [{ id: "interface", label: text("主网卡", "Primary interface"), placeholder: "eth0", hint: text("留空时按默认路由自动识别。", "Leave blank to detect it from the default route.") }, { id: "quotaGb", label: text("总流量额度（十进制 GB）", "Total quota (decimal GB)"), placeholder: "1000", type: "number", hint: text("1 GB = 1,000,000,000 字节；请与运营商计费单位保持一致。", "1 GB = 1,000,000,000 bytes. Match the provider billing unit."), required: true }, { id: "billingDay", label: text("计费周期开始日", "Billing-cycle start day"), placeholder: "1", type: "number", hint: text("允许 1–28，避免短月份日期歧义。", "Use 1–28 to avoid short-month ambiguity."), required: true }, { id: "billingTimezone", label: text("时区设定", "Timezone"), placeholder: "UTC", hint: text("使用 IANA 时区，例如 UTC 或 Asia/Tokyo。", "Use an IANA timezone such as UTC or Asia/Tokyo."), required: true }, { id: "countMode", label: text("计数方式", "Counting mode"), placeholder: "sum", type: "select", hint: text("收发相加适合双向计费；取较大值适合按方向峰值计费。", "Sum suits bidirectional billing; max uses the larger direction."), required: true, options: [{ value: "sum", label: text("接收 + 发送", "Received + transmitted") }, { value: "max", label: text("接收/发送取较大值", "Larger direction") }] }, { id: "initialUsedGb", label: text("当前周期已用基线（GB）", "Current-cycle baseline (GB)"), placeholder: "0", type: "number", hint: text("月中部署时填运营商已计费用量；新周期不会重复沿用。", "Enter provider-billed usage when deploying mid-cycle. It is not reused next cycle."), required: true }] },
  { id: "hysteria2", name: text("Hysteria2", "Hysteria2"), icon: "bolt", page: "services", summary: text("通过官方 Traffic Stats API 读取累计流量、在线计数与活动流。", "Read cumulative traffic, online counts, and streams from the official Traffic Stats API."), outcome: text("管理账号只按明确映射关联协议身份；唯一完整归属时使用统一持久化账本。", "Managed accounts use explicit protocol-identity mappings; the durable ledger is used only when ownership is complete and unambiguous."), steps: [text("启用仅回环监听的 Traffic Stats API", "Enable the loopback-only Traffic Stats API"), text("在服务器受限配置写入独立 Secret", "Store the dedicated secret in protected server configuration"), text("把实时协议身份映射到管理账号", "Map live protocol identities to managed accounts")], fields: [{ id: "endpoint", label: text("API 地址", "API endpoint"), placeholder: "http://127.0.0.1:19090", hint: text("保存时真实请求 traffic、online 与 streams；网页不会提交 Secret。", "Saving performs live traffic, online, and streams requests; the web UI never submits the secret."), required: true }, { id: "identityMappings", label: text("管理账号与协议身份映射", "Managed-account identity mappings"), placeholder: "primary=user", type: "textarea", hint: text("每行填写“管理账号=协议身份”；多个协议身份用逗号分隔。留空不会猜测归属。", "Use managed-account=protocol-identity per line; separate multiple identities with commas. Blank values are never guessed." ) }] },
  { id: "anytls", name: text("AnyTLS / sing-box", "AnyTLS / sing-box"), icon: "encrypted", page: "services", summary: text("连接本机 Clash API，并按明确的 AnyTLS 入站标签读取真实连接。", "Connect to the local Clash API and read real connections using explicit AnyTLS inbound tags."), outcome: text("只显示标签匹配且由核心返回的来源、目标、累计字节和开始时间。", "Show source, destination, cumulative bytes, and start time only for core connections matching configured tags."), steps: [text("让 Clash API 仅监听回环地址", "Bind the Clash API to loopback"), text("在服务器配置中保存 Bearer Secret", "Store the bearer secret in server configuration"), text("填写真实 AnyTLS inbound tag", "Enter real AnyTLS inbound tags")], fields: singBoxFields },
  { id: "vless", name: text("VLESS / XTLS / Reality", "VLESS / XTLS / Reality"), icon: "route", page: "services", summary: text("按官方模型关联 VLESS、XTLS Vision flow 与 Reality TLS，并用明确标签归类连接。", "Model VLESS, the XTLS Vision flow, and Reality TLS according to sing-box, then classify connections by explicit tags."), outcome: text("连接标签会体现所选安全组合；Reality 不会被误写成独立协议。", "Connection labels reflect the selected security profile; Reality is not misrepresented as a standalone protocol."), steps: [text("确认 VLESS 入站和用户 flow", "Confirm the VLESS inbound and user flow"), text("确认 TLS Reality 是否启用", "Confirm whether TLS Reality is enabled"), text("填写回环 API 与真实 inbound tag", "Enter the loopback API and real inbound tags")], fields: [...singBoxFields, { id: "securityProfile", label: text("VLESS 安全组合", "VLESS security profile"), placeholder: "standard", type: "select", hint: text("XTLS Vision 对应 xtls-rprx-vision flow；Reality 属于 TLS 配置。", "XTLS Vision maps to the xtls-rprx-vision flow; Reality belongs to TLS configuration."), required: true, options: [{ value: "standard", label: text("标准 VLESS", "Standard VLESS") }, { value: "xtls-vision", label: text("XTLS Vision", "XTLS Vision") }, { value: "reality", label: text("Reality TLS", "Reality TLS") }, { value: "xtls-vision-reality", label: text("XTLS Vision + Reality", "XTLS Vision + Reality") }] }] },
  protocolDefinition("socks5", "SOCKS5", "lan", "把明确入站标签映射为 SOCKS5 连接。", "Map explicit inbound tags to SOCKS5 connections."),
  protocolDefinition("shadowsocks", "Shadowsocks", "shield", "把明确入站标签映射为 Shadowsocks 连接。", "Map explicit inbound tags to Shadowsocks connections."),
  protocolDefinition("vmess", "VMess", "vpn_key", "接入 sing-box VMess 入站的真实连接快照。", "Map real sing-box VMess inbound connection snapshots."),
  protocolDefinition("trojan", "Trojan", "security", "接入 sing-box Trojan 入站的真实连接快照。", "Map real sing-box Trojan inbound connection snapshots."),
  protocolDefinition("tuic", "TUIC", "speed", "接入 sing-box TUIC 入站的真实连接快照。", "Map real sing-box TUIC inbound connection snapshots."),
  { id: "connections", name: text("连接活动", "Connection activity"), icon: "lan", page: "connections", summary: text("按协议、协议账号和来源 IP 聚合真实连接，并按需展开详情。", "Group real connections by protocol, protocol identity, and source IP with expandable details."), outcome: text("持续时长取最早时间；速率只由连续累计字节快照计算。", "Duration uses the earliest start; rates come only from consecutive cumulative-byte snapshots."), steps: [text("至少连接一个协议适配器", "Connect at least one protocol adapter"), text("等待连续快照建立速率", "Wait for consecutive snapshots to establish rates"), text("核对核心未提供的字段", "Review fields the core does not provide")], fields: [] },
  { id: "network", name: text("网络质量", "Network quality"), icon: "network_check", page: "network", summary: text("自定义名称、IPv4/IPv6 地址和显示顺序。", "Customize names, IPv4/IPv6 addresses, and display order."), outcome: text("每次探测保存 8 个真实 ICMP 响应点，不插值业务数据。", "Each probe keeps eight real ICMP response points without inventing business data."), steps: [text("添加 1 至 12 个目标", "Add 1 to 12 targets"), text("设置名称、地址和排序", "Set name, address, and order"), text("检查 ICMP 被禁时的不可达状态", "Check unreachable results when ICMP is blocked")], fields: [{ id: "targets", label: text("探测目标", "Probe targets"), placeholder: "Cloudflare,1.1.1.1\nGoogle IPv6,2001:4860:4860::8888", type: "textarea", hint: text("每行使用“名称,地址”；网络质量页面还提供结构化编辑器。", "Use name,address per line. A structured editor is also available on the Network page."), required: true }] },
  { id: "subscriptions", name: text("订阅配置", "Subscriptions"), icon: "qr_code_2", page: "subscriptions", summary: text("分别验证本次输入地址和服务器受保护订阅记录的实际响应。", "Validate both the newly entered address and protected subscription records with live responses."), outcome: text("服务器真实请求新地址与受保护记录；输入地址只用于本次验证，不持久化或回传。", "The server fetches both the entered address and protected records; the entered address is used once and is neither persisted nor returned."), steps: [text("确认发布服务使用有效 TLS", "Confirm the publisher uses valid TLS"), text("填写需要检查的实际订阅地址", "Enter the actual subscription URL to check"), text("服务器验证输入地址和受保护订阅均返回非空响应", "The server verifies non-empty responses from both the input and protected records")], fields: [{ id: "baseUrl", label: text("订阅验证地址", "Subscription URL to verify"), placeholder: "https://panel.example.com/subscription/token", hint: text("地址通过 HTTPS 发送到后端仅做本次真实探测；不会写入 SQLite、响应或审计。已配置时可留空直接重检受保护记录。", "The URL is sent over HTTPS for this one live probe only. It is not written to SQLite, responses, or audit. Leave it blank to recheck existing protected records."), required: true }] },
  { id: "alerts", name: text("告警中心", "Alerts"), icon: "notifications", page: "alerts", summary: text("根据真实流量、服务、网络和数据接入验证计算本地告警。", "Evaluate local alerts from real traffic, services, network probes, and integration validation."), outcome: text("通知角标只在存在未确认告警时显示，最大 99+。", "The notification badge appears only for unacknowledged alerts and caps at 99+."), steps: [text("设置流量阈值", "Set the traffic threshold"), text("设置延迟与丢包阈值", "Set latency and packet-loss thresholds"), text("确认接入异常也会生成告警", "Confirm integration failures also create alerts")], fields: [{ id: "trafficPercent", label: text("流量阈值（%）", "Traffic threshold (%)"), placeholder: "80", type: "number", hint: text("达到阈值时产生告警。", "Create an alert when this threshold is reached.") }, { id: "latencyMs", label: text("延迟阈值（ms）", "Latency threshold (ms)"), placeholder: "150", type: "number", hint: text("超过阈值的目标进入告警。", "Targets above this threshold create an alert.") }, { id: "lossPercent", label: text("丢包阈值（%）", "Packet-loss threshold (%)"), placeholder: "5", type: "number", hint: text("避免设置过低造成噪声。", "Avoid values so low that they create noise.") }] },
  { id: "audit", name: text("操作审计", "Audit log"), icon: "history", page: "audit", summary: text("记录登录、设置、告警确认和后端生命周期事件。", "Record sign-ins, settings, alert acknowledgements, and backend lifecycle events."), outcome: text("重要变更包含实际登录用户、来源与结果。", "Important changes include the actual signed-in user, source, and result."), steps: [text("确认数据库目录权限", "Confirm database directory permissions"), text("保留合适的日志周期", "Choose an appropriate retention period"), text("确保密码和 Token 不进入审计详情", "Keep passwords and tokens out of audit details")], fields: [] },
];

export const pageIntegration: Partial<Record<PageId, IntegrationId>> = {
  accounts: "hysteria2", connections: "connections", traffic: "traffic", subscriptions: "subscriptions",
  network: "network", services: "system", alerts: "alerts", audit: "audit",
};
