import type { IntegrationId, PageId } from "./types";

export interface LocalizedText { zh: string; en: string }
export interface SetupField {
  id: string;
  label: LocalizedText;
  placeholder: string;
  type?: "text" | "password" | "number" | "textarea";
  hint: LocalizedText;
  required?: boolean;
}
export interface IntegrationDefinition {
  id: IntegrationId;
  name: LocalizedText;
  icon: string;
  page?: PageId;
  summary: LocalizedText;
  outcome: LocalizedText;
  steps: LocalizedText[];
  fields: SetupField[];
}

const text = (zh: string, en: string): LocalizedText => ({ zh, en });
const singBoxFields: SetupField[] = [
  { id: "endpoint", label: text("sing-box API 地址", "sing-box API endpoint"), placeholder: "http://127.0.0.1:19091", hint: text("只接受 localhost 或回环 IP；Secret 仅从服务器受限配置读取。", "Only localhost or loopback IPs are accepted. The secret is read only from protected server configuration."), required: true },
  { id: "inboundTags", label: text("入站标签", "Inbound tags"), placeholder: "vless-in, vless-reality", hint: text("填写 sing-box 配置中的真实 inbound tag，用逗号分隔；连接只按这些显式标签归类。", "Enter real sing-box inbound tags separated by commas. Connections are classified only by these explicit tags."), required: true },
];

export const integrationDefinitions: IntegrationDefinition[] = [
  { id: "system", name: text("系统指标", "System metrics"), icon: "memory", page: "overview", summary: text("读取主机资源、运行时间与网卡累计计数器。", "Read host resources, uptime, and cumulative interface counters."), outcome: text("总览显示真实主机快照和节点名称。", "The overview shows a live host snapshot and node name."), steps: [text("确认后端仅监听回环地址", "Keep the backend bound to loopback"), text("设置节点显示名称", "Set the node display name"), text("验证 /proc 与文件系统可读", "Verify /proc and filesystem access")], fields: [{ id: "nodeName", label: text("节点显示名称", "Node display name"), placeholder: "Tokyo edge", hint: text("作为总览主标题显示，最长 80 字。", "Shown as the overview title, up to 80 characters."), required: true }] },
  { id: "traffic", name: text("流量采集", "Traffic collection"), icon: "monitoring", page: "traffic", summary: text("每分钟持久化真实网卡计数器，并生成多时间范围趋势。", "Persist real interface counters every minute and build multiple time ranges."), outcome: text("总览、账号配置额度和告警共用同一流量额度。", "Overview, account quota labels, and alerts share one traffic quota."), steps: [text("确认主网卡", "Confirm the primary interface"), text("设置总流量额度", "Set the total traffic quota"), text("等待真实采样形成趋势", "Allow real samples to build a trend")], fields: [{ id: "interface", label: text("主网卡", "Primary interface"), placeholder: "eth0", hint: text("留空时按默认路由自动识别。", "Leave blank to detect it from the default route.") }, { id: "quotaGb", label: text("总流量额度（GB）", "Total traffic quota (GB)"), placeholder: "1000", type: "number", hint: text("作为总览和所有账号的统一配置额度。", "Used as the single configured quota across overview and accounts."), required: true }] },
  { id: "hysteria2", name: text("Hysteria2", "Hysteria2"), icon: "bolt", page: "services", summary: text("通过官方 Traffic Stats API 读取累计流量、在线计数与活动流。", "Read cumulative traffic, online counts, and streams from the official Traffic Stats API."), outcome: text("账号身份只按显式映射匹配，缺失来源 IP 时明确标为核心未提供。", "Accounts use explicit identity mappings; missing source IPs remain marked as unavailable from the core."), steps: [text("启用仅回环监听的 Traffic Stats API", "Enable the loopback-only Traffic Stats API"), text("在服务器受限配置写入独立 Secret", "Store the dedicated secret in protected server configuration"), text("多账号时配置 trafficIdentities", "Configure trafficIdentities for multiple accounts")], fields: [{ id: "endpoint", label: text("API 地址", "API endpoint"), placeholder: "http://127.0.0.1:19090", hint: text("只接受 localhost 或回环 IP；网页不会提交 Secret。", "Only localhost or loopback IPs are accepted; the web UI never submits the secret."), required: true }] },
  { id: "anytls", name: text("AnyTLS / sing-box", "AnyTLS / sing-box"), icon: "encrypted", page: "services", summary: text("连接本机 Clash API，读取 sing-box 的真实连接快照。", "Connect to the local Clash API for real sing-box connection snapshots."), outcome: text("只显示核心返回的来源、目标、累计字节和开始时间。", "Show only source, destination, cumulative bytes, and start time returned by the core."), steps: [text("让 Clash API 仅监听回环地址", "Bind the Clash API to loopback"), text("在服务器配置中保存 Bearer Secret", "Store the bearer secret in server configuration"), text("验证 /connections 返回真实快照", "Verify /connections returns real snapshots")], fields: [singBoxFields[0]] },
  { id: "vless", name: text("VLESS", "VLESS"), icon: "route", page: "services", summary: text("把指定 sing-box 入站标签映射为 VLESS 连接。", "Map explicit sing-box inbound tags to VLESS connections."), outcome: text("只有标签匹配的真实连接会显示为 VLESS。", "Only real connections matching configured tags appear as VLESS."), steps: [text("确认 VLESS 由当前 sing-box 实例承载", "Confirm VLESS runs in this sing-box instance"), text("填写回环 Clash API", "Enter the loopback Clash API"), text("填写真实 inbound tag", "Enter real inbound tags")], fields: singBoxFields },
  { id: "socks5", name: text("SOCKS5", "SOCKS5"), icon: "lan", page: "services", summary: text("把指定 sing-box 入站标签映射为 SOCKS5 连接。", "Map explicit sing-box inbound tags to SOCKS5 connections."), outcome: text("未配置或标签不匹配时保持未配置，不猜测协议。", "Remain unconfigured when tags are absent or unmatched; never guess the protocol."), steps: [text("确认 SOCKS5 入站已启用", "Confirm the SOCKS5 inbound is enabled"), text("填写回环 Clash API", "Enter the loopback Clash API"), text("填写真实 inbound tag", "Enter real inbound tags")], fields: singBoxFields },
  { id: "shadowsocks", name: text("Shadowsocks", "Shadowsocks"), icon: "shield", page: "services", summary: text("把指定 sing-box 入站标签映射为 Shadowsocks 连接。", "Map explicit sing-box inbound tags to Shadowsocks connections."), outcome: text("连接归类基于服务器显式标签，不按端口或名称猜测。", "Connection classification uses explicit server tags, never port or name guesses."), steps: [text("确认 Shadowsocks 入站已启用", "Confirm the Shadowsocks inbound is enabled"), text("填写回环 Clash API", "Enter the loopback Clash API"), text("填写真实 inbound tag", "Enter real inbound tags")], fields: singBoxFields },
  { id: "connections", name: text("连接活动", "Connection activity"), icon: "lan", page: "connections", summary: text("按协议、账号和来源 IP 聚合真实连接，并按需展开详情。", "Group real connections by protocol, account, and source IP with expandable details."), outcome: text("持续时长取最早时间；速率只由连续累计字节快照计算。", "Duration uses the earliest start; rates come only from consecutive cumulative-byte snapshots."), steps: [text("至少连接一个协议适配器", "Connect at least one protocol adapter"), text("等待连续快照建立速率", "Wait for consecutive snapshots to establish rates"), text("核对核心未提供的字段", "Review fields the core does not provide")], fields: [] },
  { id: "network", name: text("网络质量", "Network quality"), icon: "network_check", page: "network", summary: text("自定义名称、IPv4/IPv6 地址和显示顺序。", "Customize names, IPv4/IPv6 addresses, and display order."), outcome: text("每次探测保存 8 个真实 ICMP 响应点，不插值业务数据。", "Each probe keeps eight real ICMP response points without inventing business data."), steps: [text("添加 1 至 12 个目标", "Add 1 to 12 targets"), text("设置名称、地址和排序", "Set name, address, and order"), text("检查 ICMP 被禁时的不可达状态", "Check unreachable results when ICMP is blocked")], fields: [{ id: "targets", label: text("探测目标", "Probe targets"), placeholder: "Cloudflare,1.1.1.1\nGoogle IPv6,2001:4860:4860::8888", type: "textarea", hint: text("每行使用“名称,地址”；网络质量页面还提供结构化编辑器。", "Use name,address per line. A structured editor is also available on the Network page."), required: true }] },
  { id: "subscriptions", name: text("订阅配置", "Subscriptions"), icon: "qr_code_2", page: "subscriptions", summary: text("显示服务器受保护配置中已有的订阅记录。", "Show subscription records already present in protected server configuration."), outcome: text("完整地址只在管理员主动复制或生成二维码时读取。", "Full URLs are read only when an administrator explicitly copies or opens a QR code."), steps: [text("确认发布服务使用 TLS", "Confirm the publisher uses TLS"), text("填写不含 Token 的公共基地址", "Enter a public base URL without a token"), text("外部可达性需另行验证", "Verify external reachability separately")], fields: [{ id: "baseUrl", label: text("订阅基地址", "Subscription base URL"), placeholder: "https://panel.example.com/subscription", hint: text("HTTPS 格式校验不代表发布器已经连通。", "HTTPS format validation does not prove the publisher is reachable."), required: true }] },
  { id: "alerts", name: text("告警中心", "Alerts"), icon: "notifications", page: "alerts", summary: text("根据真实流量、服务和网络探测计算本地告警。", "Evaluate local alerts from real traffic, service, and network probe data."), outcome: text("通知角标只在存在未确认告警时显示，最大 99+。", "The notification badge appears only for unacknowledged alerts and caps at 99+."), steps: [text("设置流量阈值", "Set the traffic threshold"), text("设置延迟与丢包阈值", "Set latency and packet-loss thresholds"), text("确认告警记录可写", "Verify acknowledgements can be stored")], fields: [{ id: "trafficPercent", label: text("流量阈值（%）", "Traffic threshold (%)"), placeholder: "80", type: "number", hint: text("达到阈值时产生告警。", "Create an alert when this threshold is reached.") }, { id: "latencyMs", label: text("延迟阈值（ms）", "Latency threshold (ms)"), placeholder: "150", type: "number", hint: text("超过阈值的目标进入告警。", "Targets above this threshold create an alert.") }, { id: "lossPercent", label: text("丢包阈值（%）", "Packet-loss threshold (%)"), placeholder: "5", type: "number", hint: text("避免设置过低造成噪声。", "Avoid values so low that they create noise.") }] },
  { id: "audit", name: text("操作审计", "Audit log"), icon: "history", page: "audit", summary: text("记录登录、设置、告警确认和后端生命周期事件。", "Record sign-ins, settings, alert acknowledgements, and backend lifecycle events."), outcome: text("重要变更包含实际登录用户、来源与结果。", "Important changes include the actual signed-in user, source, and result."), steps: [text("确认数据库目录权限", "Confirm database directory permissions"), text("保留合适的日志周期", "Choose an appropriate retention period"), text("确保密码和 Token 不进入审计详情", "Keep passwords and tokens out of audit details")], fields: [] },
];

export const pageIntegration: Partial<Record<PageId, IntegrationId>> = {
  accounts: "hysteria2", connections: "connections", traffic: "traffic", subscriptions: "subscriptions",
  network: "network", services: "system", alerts: "alerts", audit: "audit",
};
