"use client";

import { useMemo, useState } from "react";
import { copyText } from "../../lib/clipboard";
import { formatDuration, formatRate } from "../../lib/format";
import { useI18n } from "../../lib/i18n";
import type { Connection, IntegrationStatus, Protocol } from "../../lib/types";
import { IntegrationGate } from "../setup/IntegrationGate";
import { Card } from "../ui/Card";
import { Chip } from "../ui/Chip";
import { Icon } from "../ui/Icon";
import { PageHeader } from "../ui/Page";

export function ConnectionsPage({ connections, now, onToast, integration, onConfigure }: { connections: Connection[]; now: number; onToast: (message: string) => void; integration?: IntegrationStatus; onConfigure: () => void }) {
  const { t } = useI18n(); const [protocol, setProtocol] = useState<"all" | Protocol>("all"); const [ipVersion, setIpVersion] = useState<"all" | 4 | 6>("all"); const [expanded, setExpanded] = useState<Set<string>>(() => new Set());
  const protocols = useMemo(() => Array.from(new Set(connections.map((item) => item.protocol))).sort((a, b) => a.localeCompare(b)), [connections]);
  const selectedProtocol = protocol === "all" || protocols.includes(protocol) ? protocol : "all";
  const filtered = useMemo(() => connections.filter((item) => (selectedProtocol === "all" || item.protocol === selectedProtocol) && (ipVersion === "all" || item.ipVersion === ipVersion)), [connections, ipVersion, selectedProtocol]);
  const down = filtered.reduce((sum, item) => sum + (item.downloadBps ?? 0), 0); const up = filtered.reduce((sum, item) => sum + (item.uploadBps ?? 0), 0);
  const toggleExpanded = (id: string) => setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  return <div className="page-content page-enter">
    <PageHeader eyebrow={t("协议快照", "Protocol snapshots")} title={t("活动连接", "Active connections")} actions={<Chip staticChip tone={integration?.status === "ready" ? "success" : "warning"} icon="schedule">{t("5 秒轮询", "5-second polling")}</Chip>} />
    <IntegrationGate status={integration} name="连接快照采集" nameEn="Connection snapshots" description="仅展示已配置且标签匹配的协议连接；核心未返回的字段不会补成 0 或虚构内容。" descriptionEn="Only configured protocols with matching inbound tags are shown. Fields omitted by the core are never filled with zeroes or invented values." onConfigure={onConfigure} />
    <section className="summary-strip"><div><span className="summary-icon"><Icon name="group_work" /></span><p><b>{filtered.length}</b><span>{t("聚合连接组", "Connection groups")}</span></p></div><div><span className="summary-icon"><Icon name="hub" /></span><p><b>{filtered.reduce((sum, item) => sum + item.connections, 0)}</b><span>{t("活动子条目", "Active entries")}</span></p></div><div><span className="summary-icon summary-icon--down"><Icon name="south" /></span><p><b>{formatRate(down)}</b><span>{t("实时下载速率", "Live download rate")}</span></p></div><div><span className="summary-icon summary-icon--up"><Icon name="north" /></span><p><b>{formatRate(up)}</b><span>{t("实时上传速率", "Live upload rate")}</span></p></div></section>
    <Card variant="outlined" className="table-panel"><div className="table-toolbar table-toolbar--wrap"><div className="filter-chips"><Chip selected={selectedProtocol === "all"} onClick={() => setProtocol("all")}>{t("全部协议", "All protocols")}</Chip>{protocols.map((item) => <Chip key={item} selected={selectedProtocol === item} onClick={() => setProtocol(item)}>{item}</Chip>)}</div><div className="segmented-control" aria-label={t("IP 版本筛选", "IP version filter")}>{(["all", 4, 6] as const).map((item) => <button className={ipVersion === item ? "is-selected" : ""} key={item} onClick={() => setIpVersion(item)}>{item === "all" ? t("全部 IP", "All IPs") : `IPv${item}`}</button>)}</div></div>
      <div className="responsive-table connections-table"><table><colgroup><col className="connection-col--protocol" /><col className="connection-col--account" /><col className="connection-col--ip" /><col className="connection-col--entries" /><col className="connection-col--rate" /><col className="connection-col--rate" /><col className="connection-col--duration" /><col className="connection-col--expand" /></colgroup><thead><tr><th>{t("协议", "Protocol")}</th><th>{t("账号", "Account")}</th><th>{t("来源 IP", "Source IP")}</th><th>{t("活动条目", "Entries")}</th><th>{t("下载速率", "Download")}</th><th>{t("上传速率", "Upload")}</th><th>{t("持续时间", "Duration")}</th><th aria-label={t("展开详情", "Expand details")} /></tr></thead><tbody>
        {filtered.flatMap((item) => { const details = item.details ?? []; const isExpanded = expanded.has(item.id); const columns = 8; return [<tr key={item.id} className={isExpanded ? "is-expanded" : ""}>
          <td data-label={t("协议", "Protocol")}><Chip staticChip tone={item.protocol === "Hysteria2" ? "info" : "default"}>{item.protocol}</Chip></td><td data-label={t("账号", "Account")}><div className="account-inline"><span className="status-dot status-dot--online" /><strong>{item.account}</strong></div></td>
          <td data-label={t("来源 IP", "Source IP")}><div className="ip-cell"><code>{item.sourceIp}</code>{item.ipVersion ? <Chip staticChip>IPv{item.ipVersion}</Chip> : null}<button className="copy-ip-button" aria-label={t(`复制 ${item.sourceIp}`, `Copy ${item.sourceIp}`)} onClick={() => void copyText(item.sourceIp).then(() => onToast(t("来源 IP 已复制", "Source IP copied"))).catch(() => onToast(t("复制失败", "Copy failed")))}><Icon name="content_copy" size={17} /></button></div></td>
          <td data-label={t("活动条目", "Entries")}><span className="connection-count">{item.connections}</span></td><td data-label={t("下载速率", "Download")}><span className="rate rate--down"><Icon name="south" size={17} />{item.downloadBps === null ? "—" : formatRate(item.downloadBps)}</span></td><td data-label={t("上传速率", "Upload")}><span className="rate rate--up"><Icon name="north" size={17} />{item.uploadBps === null ? "—" : formatRate(item.uploadBps)}</span></td><td data-label={t("持续时间", "Duration")}><span className="mono-time">{item.connectedAt ? formatDuration((now - new Date(item.connectedAt).getTime()) / 1000) : t("核心未提供", "Not provided by core")}</span></td><td>{details.length ? <button className="connection-expand" onClick={() => toggleExpanded(item.id)} aria-expanded={isExpanded} aria-label={isExpanded ? t("收起连接详情", "Collapse connection details") : t("展开连接详情", "Expand connection details")}><Icon name={isExpanded ? "expand_less" : "expand_more"} /></button> : null}</td>
        </tr>, ...(isExpanded ? details.map((detail, index) => <tr className="connection-detail-row" key={`${item.id}-${detail.id}`}><td colSpan={columns}><div className={`connection-detail-grid ${detail.destination ? "has-destination" : "no-destination"}`}><span className="connection-detail-index">{index + 1}</span>{detail.destination ? <div><small>{t("目标地址", "Destination")}</small><code>{detail.destination}</code></div> : null}<div><small>{t("持续时间", "Duration")}</small><strong>{detail.connectedAt ? formatDuration((now - new Date(detail.connectedAt).getTime()) / 1000) : "—"}</strong></div><div className="rate rate--down"><small>{t("下载", "Download")}</small><strong><Icon name="south" size={16} />{detail.downloadBps === null ? "—" : formatRate(detail.downloadBps)}</strong></div><div className="rate rate--up"><small>{t("上传", "Upload")}</small><strong><Icon name="north" size={16} />{detail.uploadBps === null ? "—" : formatRate(detail.uploadBps)}</strong></div></div></td></tr>) : [])]; })}
      </tbody></table></div>{!filtered.length ? <div className="table-empty"><Icon name="link_off" size={28} /><strong>{t("没有可显示的活动连接", "No active connections to show")}</strong><span>{t("仅显示已配置协议且 inbound tag 匹配的真实连接", "Only real connections whose protocol and inbound tag are configured are shown")}</span></div> : null}
    </Card>
  </div>;
}
